name: flutter_charset_detector_darwin
description: Darwin implementation of the flutter_charset_detector plugin.
version: 1.1.0
homepage: https://github.com/amake/flutter_charset_detector

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_charset_detector_platform_interface: ^1.1.0
  # flutter_charset_detector_platform_interface:
  #   path: ../flutter_charset_detector_platform_interface

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_charset_detector
    platforms:
      ios:
        pluginClass: FlutterCharsetDetectorPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterCharsetDetectorPlugin
        sharedDarwinSource: true
