name: flutter_charset_detector_web_example
description: "Demonstrates how to use the flutter_charset_detector_web plugin."
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_charset_detector_web:
    path: ../

  cupertino_icons: ^1.0.2

  file_picker: ^6.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
