name: flutter_charset_detector_platform_interface
description: A common platform interface for the flutter_charset_detector plugin.
version: 1.1.0
homepage: https://github.com/amake/flutter_charset_detector

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
